### ISSUE TITLE
does not add anchors to headings using GitHub’s algorithm 

### ISSUE THREAD

**Issue by endiliey** [remarkjs/remark-slug#11]
### Subject of the issue

remark-slug does not add anchors to headings using GitHub’s algorithm.

This probably got to do with `toString` from https://github.com/syntax-tree/mdast-util-to-string

### Your environment

N/A. Does not matter. 

### Steps to reproduce

Example you have markdown

```md
## <a name="foo"></a> Foo

## <a name="foo"></a> _Foo_
```

Use runkit for easy reproduction

https://runkit.com/endiliey/5dd56d8045205a0013aec93d

![image](https://user-images.githubusercontent.com/17883920/69259154-5b4c3900-0bf0-11ea-8675-c374e2f5a95b.png)

### Expected behaviour

Slug should be like GitHub https://gist.github.com/endiliey/4516bbf630b0f34eeabe8900733cfbf6#-foo

`-foo` and `-foo-1`

### Actual behaviour

Slug is `a-namefooa-foo` and `a-namefooa-foo-1`

**Comment by wooorm** [comment]
We can’t do that easily, unfortunately, to solve it we’d need to include a whole HTML parser. That is a very intensive task.

If you’re going to HTML, instead, you can use [rehype-slug](https://github.com/rehypejs/rehype-slug).

Alternatively, you can set `node.data.hProperties.id` yourself, and bring that parser in if you want!

And lastly, you could also not use HTML in headings ;) HTML in Markdown has many downsides.

**Comment by wooorm** [comment]
Btw, thanks for distilling the problem down so much! That makes me able to answer quickly.

But on the other hand, maybe there is a bigger question you have, that I can also answer?

**Comment by endiliey** [comment]
Actually i don't mind with current behavior. Just opening up this issue just in case someone will open up an issue in our repo saying this.

Now when they did, I will tell them to see this issue 😆 

Thanks for the great work

**Comment by wooorm** [comment]
Ahh alright, good! Yeah, it’s good that this is documented 👍
If you have thoughts on how and where to add this to the docs, that’s also welcome!

Thanks Endi!
