### ISSUE TITLE
When creating slugs (within gatsby-plugin-mdx), accents make the anchors fail

### ISSUE THREAD

**Issue by kuworking** [remarkjs/remark-slug#12]
If in a mdx file I have something like 

```
# This is my áccentuated title
```

The id generated keeps the accent

```
id="This-is-my-áccentuated-title"
```

But then, the link that you can recreate with `"to="mywebpage#This-is-my-áccentuated-title"` doesn't go to the anchor because of the accent (at least what I'm seeing in Chrome)

Could it be possible to remove accents from strings?

**Comment by wooorm** [comment]
This should work, tested in Chrome and Safari: https://gist.github.com/wooorm/870867683378861936701d2b6f560be5#this-is-my-áccentuated-title

**Comment by kuworking** [comment]
It is true, but somehow I get consistent results within my Gatsby site, any anchor with an accent is ignored, any anchor without an accent works

Trying to see what's going on (anchors through `<Link>'  element)

**Comment by wooorm** [comment]
It’s unlikely a problem here, rather, probably gatsby, gatsby-mdx, or another plugin your using?

This project does the `id`. Exactly the way GitHub does it. It sounds like there’s a unicode problem in the place that creates the links.

**Comment by kuworking** [comment]
Here you have a repo

https://github.com/kuworking/link_anchors_accents

It doesn't use anything, just `<Link>`, and in my computer the link to the accentuated id doesn't work

It is either a problem of Gatsby of a problem with ... my computer (!?), but it doesn't seem related to _remark-slug_, what do you think?

**Comment by wooorm** [comment]
Indeed, it’s not a problem here. I don’t use React or Gatsby, so I can’t help you with that. It sounds like the `Link` component doesn’t support unicode!

**Comment by wooorm** [comment]
Thanks for the repro btw, you should show that to Gatsby folks! (and maybe link to this issue as well!)

**Comment by sebtiz13** [comment]
Hello sorry for reopen this issue but i have same problems with gridsome (Vue.JS).
vue-router doesn't support anchor with accent (https://github.com/vuejs/vue-router/issues/1581).

So why not simply remove accents or maybe just add a function to customize the slug ?

Another "lazy" solution would be to add support of "remark-attr" and get id from hProperties/htmlAttributes to fix the problem with custom id.

Exemple: 
```
## This is my áccentuated title {id="this-is-my-accentuated-title"}
```

directly get id "this-is-my-accentuated-title" without more treatment and the responsibility it's on editor of markdown.
