### ISSUE TITLE
remark-slug doesn't take current URL into consideration

### ISSUE THREAD

**Issue by mhatvan** [remarkjs/remark-slug#13]
### Problem

`remark-slug` currently just takes the text content of the heading and slugifies it for `remark-autolink-headings`, I assume.

Unfortunately, I am on a nested URL like: `/blog/contributing-to-open-source-projects-the-right-way` and not on the root path, therefore the a link redirects me to the root page instead of staying on the current page and jumping down.

Is there any solution or config option for that?

### Expected behaviour

Jump to the anchor

**Comment by ChristianMurphy** [comment]
@mhatvan adds `id` attributes to elements, it doesn't change links.
You can use anchor links, which don't switch what page you are on.
https://www.rapidtables.com/web/html/link/html-anchor-link.html

**Comment by mhatvan** [comment]
Yea I am aware of that but I meant that remark-autolink-headings takes the slug provided by remark-slug.

In case you are interested: I found out that the issue that I am encountering is indeed not relevant to this library, but the framework that I am using.

https://www.ryanfiller.com/blog/things-svelte-and-sapper-cant-do-yet#sappers-router-doesnt-work-with-hash-links
